import Layout from "@/components/Layout";
import Head from "next/head";
import profilePic from "../../public/images/profile/developer-pic-1.png";
import Image from "next/image";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import TransitionEffect from "@/components/TransitionEffect";
// import Image from "next/image";
// import { Inter } from "next/font/google";
// import styles from "@/styles/Home.module.css";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Paul Kiattikhunphan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/PK.ico" />
      </Head>
      <TransitionEffect />
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0 md:p-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full">
              {/* //profile picture is here: */}
              <Image
                src={profilePic}
                alt="Paul"
                className="w-full h-auto lg:hidden md:inline-block md:w-full"
                //priority attribute, when true image is considered high priority and preloads. Everytime we refresh, the image will reloads

                priority
                //sizes attribute
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
              />
            </div>
            <div className="w-1/2 flex flex-col item-center self-center lg:w-full lg:text-center">
              {/* pass in text that we want to animate */}
              <AnimatedText
                text="Bridging Imagination & Technology"
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!3xl"
              />
              <p className="mt-0 mb-2 text-base font-medium md:text-sm sm:text-xs text-primary dark:text-primaryDark">
                By Paul Kiattikhunphan
              </p>
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                Welcome to my online space! As a skilled developer and student
                at the University of Virginia, I&apos;m dedicated to turning ideas
                into functional and engaging web applications. Here, you can
                explore my latest projects and articles. So, grab a virtual cup
                of coffee from your desk, make yourself comfortable, and let&apos;s
                explore together!
              </p>
              {/* Resume Button  */}
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="/Kiattikhunphan_Resume.pdf"
                  target={"_blank"}
                  //download={true} makes it so that it downloads to the downloads folder
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:text-dark dark:bg-light hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 mx:px-4 md:text-base"
                  download={true}
                >
                  Resume
                  <LinkArrow className={"w-6 ml-1"}></LinkArrow>
                </Link>
                {/* Contact me Button */}
                <Link
                  href="mailto:ppk6chf@virginia.edu"
                  target={"_blank"}
                  className="ml-4 text-lg font-medium capitalize text-dark dark:text-light md:text-base"
                >
                  Contact Me!
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
      </main>
    </>
  );
}
